// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdTV8McfZqKT-gWXf-K2auoJsAq8Ntzrs',
    appId: '1:365242308647:web:be3e76b78bff4d9ae31602',
    messagingSenderId: '365242308647',
    projectId: 'unihousing-65b12',
    authDomain: 'unihousing-65b12.firebaseapp.com',
    storageBucket: 'unihousing-65b12.appspot.com',
    measurementId: 'G-VCQBS4L5Z7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCK1eh3ggIaIto2rSfbG00AUzkcE4s7sd4',
    appId: '1:365242308647:android:e4875297c1418bc7e31602',
    messagingSenderId: '365242308647',
    projectId: 'unihousing-65b12',
    storageBucket: 'unihousing-65b12.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5n5cDsD-g4mfZJwUCgMf4Lwra43PjBtI',
    appId: '1:365242308647:ios:092549d8797d9a11e31602',
    messagingSenderId: '365242308647',
    projectId: 'unihousing-65b12',
    storageBucket: 'unihousing-65b12.appspot.com',
    iosClientId:
        '365242308647-bbhi2vbejppgnl0vgmb4pa977u5srg10.apps.googleusercontent.com',
    iosBundleId: 'com.example.uniHousing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5n5cDsD-g4mfZJwUCgMf4Lwra43PjBtI',
    appId: '1:365242308647:ios:092549d8797d9a11e31602',
    messagingSenderId: '365242308647',
    projectId: 'unihousing-65b12',
    storageBucket: 'unihousing-65b12.appspot.com',
    iosClientId:
        '365242308647-bbhi2vbejppgnl0vgmb4pa977u5srg10.apps.googleusercontent.com',
    iosBundleId: 'com.example.uniHousing',
  );
}
